urls.py
#!/usr/bin/python
# coding=UTF-8

from django.conf.urls.defaults import *

import admin
import directory.models
import directory.views
import django.contrib.auth.views
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(u'',
    (ur'^$', directory.views.homepage),
    (ur'^accounts/login/$', u'django.contrib.auth.views.login'),
    (ur'^admin/', include(admin.site.urls)),
    (ur'^ajax/check_login', directory.views.ajax_check_login),
    (ur'^ajax/create_user', directory.views.create_user),
    (ur'^ajax/delete', directory.views.ajax_delete),
    (ur'^ajax/download/(Email|Entity|Phone|Status|Tag|URL)', directory.views.ajax_download_model),
    (ur'^ajax/login', directory.views.ajax_login_request),
    (ur'^ajax/logout', directory.views.ajax_logout_request),
    (ur'^ajax/new/Entity', directory.views.new_Entity),
    (ur'^ajax/profile/(\d+)', directory.views.ajax_profile),
    (ur'^ajax/saveimage/(\d+)', directory.views.saveimage),
    (ur'^ajax/save', directory.views.save),
    (ur'^ajax/search', directory.views.ajax_search),
    (ur'^ajax/undo', directory.views.undo),
    (ur'^changelog', directory.views.changelog),
    (ur'^(create/Entity)', directory.views.redirect),
    (ur'^(create/Location)', directory.views.redirect),
    (ur'^manage/Entity/?(\d*)', directory.views.modelform_Entity),
    (ur'^manage/Location/?(\d*)', directory.views.modelform_Location),
    (ur'^password_reset/$', 'django.contrib.auth.views.password_reset'),
    (ur'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (ur'^profile/images/(\d+)', directory.views.image),
    (ur'^profile/(new)$', directory.views.profile_new),
    (ur'^profile/(\d+)$', directory.views.profile_existing),
    (ur'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (ur'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
    (ur'^static/js/directory_search.js', directory.views.directory_search),
    # Example:
    # (r'^directory/', include('directory.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
      (r'^%s(?P<path>.*)$' % (settings.MEDIA_URL[1:],),  'serve', {
        'document_root': settings.MEDIA_ROOT,
        'show_indexes': True }),)

models.py
#!/usr/bin/python
# coding = UTF-8

from django.contrib import admin
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import models

import datetime
import directory
import django.forms
import re

OFFICE_CHOICES = (
  (u'CN', u'Chicago North Office, Illinois, USA'),
  (u'CS', u'Chicago South Office, Illinois, USA'),
  (u'WH', u'Wheaton Office, Illinois, USA'),
  (u'SY', u'Sydney Office, New South Wales, Australia'),
  )

EDIT_CHOICES = (
  (u'a', u'Foreign key relationship changed.'),
  (u'b', u'Image changed.'),
  (u'c', u'Instance created.'),
  (u'd', u'Instance deleted.'),
  (u'e', u'Many to many relationship added.'),
  (u'f', u'Many to many relationship deleted.'),
  (u'g', u'One to many relationship added.'),
  (u'h', u'One to many relationship deleted.'),
  (u'i', u'Text changed.'),
  )

TIME_ZONE_CHOICES = (
  (None, "Select"),
  ("1.0", "A: Paris, +1:00"),
  ("2.0", "B: Athens, +2:00"),
  ("3.0", "C: Moscow, +3:00"),
  ("4.0", "D: Dubai, +4:00"),
  ("4.5", "-: Kabul, +4:30"),
  ("5.0", "E: Karachi, +5:00"),
  ("5.5", "-: New Delhi, +5:30"),
  ("5.75", "-: Kathmandu, :5:45"),
  ("6.0", "F: Dhaka, +6:00"),
  ("6.5", "-: Rangoon, +6:30"),
  ("7.0", "G: Jakarta, +7:00"),
  ("8.0", "H: Kuala Lumpur, +8:00"),
  ("9.0", "I: Tokyo, +9:00"),
  ("9.5", "-: Adelaide, +9:30"),
  ("10.0", "K: Sydney, +10:00"),
  ("10.5", "-: Lord Howe Island, +10:30"),
  ("11.0", "L: Solomon Islands, +11:00"),
  ("11.5", "-: Norfolk Island, +11:50"),
  ("12.0", "M: Auckland, +12:00"),
  ("12.75", "-: Chatham Islands, +12:45"),
  ("13.0", "-: Tonga, +13:00"),
  ("14.0", "-: Line Islands, +14:00"),
  ("-1.0", "N: Azores, -1:00"),
  ("-2.0", "O: Fernando de Norohna, -2:00"),
  ("-3.0", "P: Rio de Janiero, -3:00"),
  ("-3.5", "-: St. John's, -3:50"),
  ("-4.0", "Q: Santiago, -4:00"),
  ("-4.5", "-: Caracas, -4:30"),
  ("-5.0", "R: New York City, -5:00"),
  ("-6.0", "S: Chicago, -6:00"),
  ("-7.0", "T: Boulder, -7:00"),
  ("-8.0", "U: Los Angeles, -8:00"),
  ("-9.0", "V: Anchorage, -9:00"),
  ("-9.5", "-: Marquesas Islands, -9:30"),
  ("-10.0", "W: Hawaii, -10:00"),
  ("-11.0", "X: Samoa, -11:00"),
  ("-12.0", "Y: Baker Island, -12:00"),
  ("0.0", "Z: London, +0:00"),
  )

FOREIGN_KEY_RELATIONSHIP_CHANGED = u'a'
IMAGE_CHANGED = u'b'
INSTANCE_CREATED = u'c'
INSTANCE_DELETED = u'd'
MANY_TO_MANY_RELATIONSHIP_ADDED = u'e'
MANY_TO_MANY_RELATIONSHIP_DELETED = u'f'
MANY_TO_ONE_RELATIONSHIP_ADDED = u'g'
MANY_TO_ONE_RELATIONSHIP_DELETED = u'h'
TEXT_CHANGED = u'i'

class EditTrail(models.Model):
    change_set = models.IntegerField()
    change_type = models.CharField(max_length = 1, choices = EDIT_CHOICES)
    content_object = generic.GenericForeignKey(u'content_type', u'object_id')
    content_type = models.ForeignKey(ContentType)
    field_name = models.TextField(null = True, blank = True)
    foreign_key_added = generic.GenericForeignKey()
    foreign_key_deleted = generic.GenericForeignKey()
    in_effect = models.BooleanField()
    instance = generic.GenericForeignKey()
    ip = models.IPAddressField()
    object_id = models.PositiveIntegerField()
    session = models.TextField(null = True, blank = True)
    text_after = models.TextField(null = True, blank = True)
    text_before = models.TextField(null = True, blank = True)
    timestamp = models.DateTimeField(default = datetime.datetime.now, blank =
      True)
    username = models.TextField(null = True, blank = True)
    def format_timestamp(self):
        return directory.functions.format_timestamp(self.timestamp)

class ExtensionField(models.TextField):
    def __init__(self, *arguments, **keywords):
        models.TextField.__init__(self, *arguments, **keywords)

def gps_validator(value):
    # Create a normalized working copy of the value.
    working_copy = value
    working_copy = working_copy.replace(u'\n', u',')
    working_copy = working_copy.replace(u'\r', u',')
    working_copy = re.sub(ur',*$', '', working_copy)
    working_copy = re.sub(ur',+', u',', working_copy)
    if not u',' in working_copy and not \
      re.match(ur'.* .* .*', working_copy):
        working_copy = working_copy.replace(u' ', u',')
    working_copy = re.sub(u'[\00B0\2018\2019\201C\201D\'"]', ' ', working_copy)
    working_copy = working_copy.replace(u',', u', ')
    working_copy = re.sub(ur'\s+', u' ', working_copy)
    working_copy = working_copy.strip()
    working_copy = working_copy.upper()
    # Test the normalized working copy against regular expressions for different kinds of GPS format.
    if re.match(ur'[-NS]? ?\d{1,3} [0-5]\d [0-5]\d(\.\d+)[NS]?, [-EW]? ?\d{1,3} [0-5]\d [0-5]\d(\.\d+)[EW]?', working_copy):
        return working_copy
    elif re.match(ur'[-NS]? ?\d{1,3} [0-5]\d(\.\d+)[NS]?, [-EW]? ?\d{1,3} [0-5]\d(\.\d+)[EW]?', working_copy):
        return working_copy
    elif re.match(ur'[-NS]? ?\d{1,3}(\.\d+)[NS]?, [-EW]? ?\d{1,3}(\.\d+)[EW]?', working_copy):
        return working_copy
    else:
        raise ValidationError(u'We could not recognize this as a valid GPS coordinate.')

class GPSField(models.TextField):
    default_error_messages = {
        u'invalid': u'We could not recognize this as a valid GPS coordinate.',
      }
    default_validators = [gps_validator]

class Increment(models.Model):
    pass

class Location(models.Model):
    identifier = models.TextField(blank = True)
    description = models.TextField(blank = True)
    office = models.CharField(max_length=2, choices=OFFICE_CHOICES, blank =
      True)
    postal_address = models.TextField(blank = True)
    room = models.TextField(blank = True)
    coordinates = GPSField(blank = True)

class TextURLField(models.URLField):
    def __init__(self, *arguments, **keywords):
        models.URLField.__init__(self, *arguments, **keywords)
    def get_internal_type(self):
        return u'TextField'

# This class is basically the "Person" class; however, it is called "Entity"
# to emphasize that it is intended to accommodate people, offices,
# organizational units, and possibly other areas.
class Entity(models.Model):
    active = models.BooleanField(blank = True)
    department = models.ForeignKey(u'self', blank = True, null =
      True, related_name = u'member')
    description = models.TextField(blank = True)
    gps = GPSField()
    image_mimetype = models.TextField(blank = True, null = True)
    is_invisible = models.BooleanField(default = False)
    location = models.ForeignKey(u'self', blank = True, null = True,
      related_name = u'occupant')
    name = models.TextField(blank = True, default =
      directory.settings.PLACEHOLDER_NAME)
    observes_daylight_saving_time = models.BooleanField(blank = True, default
      = True)
    other_contact = models.TextField(blank = True)
    postal_address = models.TextField(blank = True)
    publish_externally = models.BooleanField(blank = True)
    reports_to = models.ForeignKey(u'self', blank = True, null = True,
      related_name = u'subordinate')
    start_date = models.DateField(blank = True, null = True)
    time_zone = models.CharField(max_length = 5, null = True, choices =
      TIME_ZONE_CHOICES)
    title = models.TextField(blank = True)
    class Meta:
        permissions = (
          ("view_changelog", "View the editing changelog"),
          )

class Tag(models.Model):
    entity = models.ForeignKey(Entity)
    is_invisible = models.BooleanField(default = False)
    text = models.TextField(blank = True)
    def __eq__(self, other):
        try:
            return self.text == other.text
        except:
            return False

class TextEmailField(models.EmailField):
    #entity = models.ForeignKey(Entity)
    def __init__(self, *arguments, **keywords):
        models.EmailField.__init__(self, *arguments, **keywords)
    def get_internal_type(self):
        return u'TextField'

class Email(models.Model):
    email = TextEmailField()
    entity = models.ForeignKey(Entity)
    is_invisible = models.BooleanField(default = False)

class URL(models.Model):
    entity = models.ForeignKey(Entity)
    url = TextURLField()
    is_invisible = models.BooleanField(default = False)

class Phone(models.Model):
    description = models.TextField(blank = True, null = True)
    entity = models.ForeignKey(Entity, blank = True)
    is_invisible = models.BooleanField(default = False)
    number = models.TextField(blank = True)
    def __eq__(self, other):
        try:
            return self.remove_formatting() == other.remove_formatting()
        except:
            return False
    def remove_formatting(self):
        return re.sub(ur'\D', u'', str(self))

class Status(models.Model):
    datetime = models.DateTimeField(default = datetime.datetime.now, blank = True)
    entity = models.ForeignKey(Entity, blank = True)
    is_invisible = models.BooleanField(default = False)
    text = models.TextField(blank = True)
    username = models.TextField(blank = True)
    def format_timestamp(self):
        return directory.functions.format_timestamp(self.datetime)

class EntityForm(django.forms.ModelForm):
    class Meta:
        model = Entity
        fields = (u'name', u'description', u'phone', u'department',
          u'postal_address', u'reports_to', u'active', u'publish_externally')

class LocationForm(django.forms.ModelForm):
    class Meta:
        model = Location

templates/base.html
{% block dtd %}<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">{% endblock dtd %}
{% block html_tag %}<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">{% endblock html_tag %}
    {% block head %}<head>
        <title>{% block head_title %}{{ page.title }}{% endblock head_title %}</title>
        {% block head_favicon %}<link rel="icon" href="/static/favicon.ico" type="x-icon" />
        <link rel="shortcut icon" href="/static/favicon.ico" type="x-icon" />{% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_author%}{% endblock head_meta_author %}
            {% block head_meta_charset %}<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />{% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}<meta http-equiv="Content-Language" value="en-US" />{% endblock head_meta_contentlanguage %}
            {% block head_meta_description %}{% endblock head_meta_description %}
            {% block head_meta_keywords %}{% endblock head_meta_keywords %}
            {% block head_meta_othertags %}{% endblock head_meta_othertags %}
            {% block head_meta_refresh %}{% endblock head_meta_refresh %}
            {% block head_meta_robots %}{% endblock head_meta_robots %}
        {% endblock head_meta %}
        {% block head_rss %}{% endblock head_rss %}
        {% block head_css %}
            {% block head_css_site %}<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
<link rel="stylesheet" type="text/css"
href="/static/css/smoothness/jquery-ui-1.8.2.custom.css" />{% endblock head_css_site %}
            {% block head_css_section %}{% endblock head_css_section %}
            {% block head_css_page %}{% endblock head_css_page %}
        {% endblock head_css %}
        {% block head_section %}{% endblock head_section %}
        {% block head_page %}{% endblock head_page %}
    </head>{% endblock head %}
    {% block body %}<body>
        {% block body_preamble_site %}{% endblock body_preamble_site %}
        {% block body_preamble_section %}{% endblock body_preamble_section %}
        {% block body_preamble_page %}{% endblock body_preamble_page %}
        <div id="sidebar">
        {% block body_sidebar %}{% endblock body_sidebar %}
        </div>
        <div id="content">
        {% block body_content %}
            <div id="header">
            {% block body_header %}
                {% block body_header_banner %}{% endblock body_header_banner %}
                {% block body_header_title %}<h1>{{ page.title }}</h1>{% endblock body_header_title %}
                {% block body_header_breadcrumb %}{{ page.breadcrumb }}{% endblock body_header_breadcrumb %}
            {% endblock body_header %}
            </div>
            {% block body_site_announcements %}{% endblock body_site_announcements %}
            {% block body_notifications %}<div id="notifications"></div>{% endblock body_notifications %}
            {% block body_main %}{% endblock body_main %}
        {% endblock body_content %}
        </div>
        <div id="footer">
        {% block body_footer %}
            {% block body_footer_breadcrumb %}{{ page.breadcrumb }}{% endblock body_footer_breadcrumb %}
            {% block body_footer_legal %}{% endblock body_footer_legal %}
        {% endblock body_footer %}
        </div>
    </body>{% endblock body %}
    {% block footer %}
        {% block footer_javascript %}
            {% block footer_javascript_site %}
                {% if settings.DEBUG %}
                    <script language="JavaScript" type="text/javascript" src="/static/js/jquery.js"></script>
                    <script language="JavaScript" type="text/javascript" src="/static/js/jquery-ui.js"></script>
                    <script language="JavaScript" type="text/javascript" src="/static/js/jquery.jeditable.js"></script>
                    <script language="JavaScript" type="text/javascript" src="/static/js/ajaxfileupload.js"></script>
                {% else %}
                    <script language="JavaScript" type="text/javascript" src="/static/js/directory_base.js"></script>
                {% endif %}
{% endblock footer_javascript_site %}
            {% block footer_javascript_section %}{% endblock footer_javascript_section %}
            {% block footer_javascript_page %}{% endblock footer_javascript_page %}
        {% endblock footer_javascript %}
    {% endblock footer %}
</html>

templates/changelog.html
{% extends "base.html" %}
{% block head_title %}Changelog{% endblock head_title %}
{% block body_header_title %}<h1>Changelog</h1>{% endblock body_header_title %}
{% block body_main %}
    {% for message in messages %}
        {% if forloop.counter == settings.INITIAL_RESULTS %}<div class="remainder">{% endif %}
            <p>{{ message.message|safe }}<br />
            <span class="timestamp">{{ message.timestamp }}</span> &rarr;
            <a href="JavaScript:undo({{ message.change_set }});">Undo</a></p>
    {% endfor %}
    </div>
    {% if messages|length > settings.INITIAL_RESULTS %}
        <p class="expand_link"><strong><a href="JavaScript:expand();"><span
        class="emphasized">+</span> Show all</a></strong></p>
    {% endif %}
{% endblock body_main %}
{% block footer_javascript_page %}
    <script language="JavaScript" type="text/javascript">
        <!--

            function expand()
                {
                $(".expand_link").hide();
                $(".remainder").show();
                }

            send_notification = function(message)
                {
                $("#notifications").html("<p>" + message + "</p>");
                setTimeout("$('#notifications').show('slow').delay(" +
                  (5000 + message.length * 2) + ").hide('slow');", 0);
                }


            function undo(change_set)
                {
                $.ajax({
                    data:
                        {
                        change_set: change_set,
                        },
                    error: function(XMLHttpRequest)
                        {
                        send_notification(XMLHttpRequest.responseText);
                        },
                    success: function()
                        {
                        send_notification("This change has been undone.");
                        },
                    url: "/ajax/undo",
                    });
                }

        // -->
    </script>
{% endblock footer_javascript_page %}

templates/main.html
{% extends "base.html" %}

templates/modelform.html
{% extends "base.html" %}
{% block head_title %}Manage {{ title }}{% endblock head_title %}
{% block body_header_title %}<h1>{{ title }}</h1>{% endblock body_header_title %}
{% block body_main %}
<form action="" method="POST">
    <table>
        {{ form }}
        <tr>
            <th>&nbsp;</th>
            <td><input type="submit" /></td>
        </tr>
    </table>
</form>
{% endblock body_main %}
{% block head_css_page %}
<style type="text/css">
<!--

body
    {
    padding-left: 40px;
    padding-right: 40px;
    }

.even
    {
    }

.odd input
    {
    }

.odd textarea
    {
    }

input.text
    {
    border: 1px solid silver;
    font-size: larger;
    font-weight: bold;
    height: 1.5em;
    width: 100%;
    }

.odd
    {
    background-color: #eeeeee;
    }

.odd input
    {
    background-color: #f4f4f4;
    }

.odd textarea
    {
    background-color: #f4f4f4;
    }

table
    {
    border-spacing: 0;
    width: 100%;
    }

td
    {
    padding: 4px;
    width: 100%;
    }

th
    {
    padding: 4px;
    font-style: normal;
    font-weight: normal;
    text-align: right;
    }

textarea
    {
    border: 1px solid silver;
    font-family: Verdana, Arial, sans;
    font-size: larger;
    font-weight: bold;
    height: 1.5em;
    width: 100%;
    }

textarea#id_description
    {
    height: 10em;
    }

// -->
</style>
{% endblock head_css_page %}
{% block footer_javascript_page %}
<script language="JavaScript" type="text/javascript">
<!--

    $("input:text").addClass("text");
    $("tr:even").addClass("odd");
    $("tr:odd").addClass("even");

// -->
</script>
{% endblock footer_javascript_page %}

templates/profile_internal.html
<h2>People, etc.</h2>

<div class="deletion">
<span class="delete" id="Entity_{{ id }}">Delete "{{ entity.name }}"</span>
</div>
<h3 id="Entity_name_{{ id }}" title="Click to edit." class="edit"
>{{ entity.name }}</h3>
<div class="image">
    <form id="image_upload" name="image_upload"
      action="/ajax/saveimage/{{ id }}" method="POST"
      enctype="multipart/form-data">
        {% if entity.image_mimetype %}
            <img class="profile" src="/profile/images/{{ id }}" /><br />
        {% else %}
            <div id="image_slot"></div>
            Upload image:<br />
        {% endif %}
        <input type="file" name="image" id="image" /><br />
        <button class="button" id="upload"
          onclick="return PHOTO_DIRECTORY.ajax_file_upload({{ id }});"
          >Upload</button>
    </form>
</div>
<p>Title: <strong id="Entity_title_{{ id }}" title="Click to edit."
  class="edit">{{ entity.title }}</strong></p>

<p>Description: <strong id="Entity_description_{{ id }}" title="Click to edit."
  class="edit_textarea">{{ entity.description }}</strong></p>

<p>Tags: <strong>
    {% for tag in tags %}
        <span class="tag">{{ tag.text }}</span>&nbsp;<span class="delete" id="Tag_{{ tag.id }}">&#10008;</span>&nbsp;&nbsp;
    {% endfor %}
    <span class="edit_textarea" id="Entity_tag_new_{{ id }}"></span>
</strong></p>

<p>Phone: <strong>
    {% for phone in phones %}
        <span id="Phone_{{ phone.id }}" class="edit"
          title="Click to edit.">{{ phone.number }}</span>
        <span class="delete" id="Phone_{{ phone.id }}">&#10008;</span> &nbsp;
    {% endfor %}
    <span class="edit" title="Click to add." id="Phone_new_{{ id }}"></span>
</strong></p>
<p>Email: <strong>
    {% for email in emails %}
    <a id="Email_{{ email.id }}" class="edit_rightclick"
      title="RIGHT click to edit." href="mailto:{{ email.email }}"
      >{{ email.email }}</a>
    <span class="delete" id="Email_{{ email.id }}">&#10008;</span> &nbsp;
    {% endfor %}
    <span class="edit" title="Click to edit." id="Email_new_{{ id }}"></span>
</strong></p>
<p>Webpages: <strong>
    {% for url in urls %}
        <a id="URL_url_{{ url.id }}" class="edit_rightclick"
          title="RIGHT click to edit."
          href="{% if ":" not in url.url %}http://{% endif %}{{ url.url }}">{{ url.url }}</a>
        <span class="delete" id="URL_{{ url.id }}">&#10008;</span> &nbsp;
    {% endfor %}
    <span class="edit" title="Click to add." id="URL_new_{{ id }}"></span>
</strong></p>

<p>GPS: <strong>
    {% if gps %}
        <a class="edit_rightclick" id="Entity_gps_{{ id }}"
          href="{{ gps_url }}">{{ gps }}</a>
    {% else %}
        <span class="edit" id="Entity_gps_{{ id }}"></span>
    {% endif %}
</strong></p>

<p>Postal address:
    <strong class="edit_textarea" title="Click to edit."
      id="Entity_postal_address_{{ id }}">{{ entity.postal_address }}</strong></p>

<p>Other contact information:
    <strong class="edit_textarea" title="Click to edit."
      id="Entity_other_contact_{{ id }}">{{ entity.other_contact }}</strong></p>

<p>Time zone:
    <select name="time_zone" id="time_zone"
      onchange="PHOTO_DIRECTORY.update_autocomplete('Entity_time_zone_{{ id }}', 'time_zone');">
        {% for time_zone in time_zones %}
            <option value="{{ time_zone.0 }}"
                {% if time_zone.0 == entity.time_zone %}
                    selected
                {% endif %}
            >{{ time_zone.1 }}</option>
        {% endfor %}
    </select><br />
Observes daylight saving time: <input type="checkbox"
name="observes_daylight_saving_time" id="observes_daylight_saving_time"
onchange="PHOTO_DIRECTORY.update_autocomplete('Entity_observes_daylight_saving_time_{{ id }}', 'observes_daylight_saving_time');"
{% if entity.observes_daylight_saving_time %}
  checked="checked"
{% endif %}
    /></p>

{% if entity.time_zone != None %}
<p>Local time:
<span id="local_time_zone">{{ entity.time_zone }}</span>
<span id="local_time"></span></p>
{% endif %}

<p>Department: <strong>
    <a href="/?query={{ query }}&id={{ entity.department.id }}"
      onclick="load_profile({{ entity.department.id }}); return false;"
      >{{ entity.department.name }}</a> &nbsp;
    <select name="department" id="department" class="autocomplete"
      onchange=
      "PHOTO_DIRECTORY.update_autocomplete('Entity_department_{{ id }}', 'department');">
        <option 
          {% if not entity.department %}
             selected="selected"
          {% endif %}
          value="department.-1"></option>
        {% for department in entities %}
        <option
          {% if department.id == entity.department %}
              selected="selected"
          {% endif %}
          value="department.{{ department.id }}">{{ department.name }}</option>
        {% endfor %}
</select></strong></p>

<p>Location: <strong>
    <a href="/?query={{ query }}&id={{ entity.location.id }}"
      onclick="load_profile({{ entity.location.id }}); return false;"
      >{{ entity.location.name }}</a> &nbsp;
    <select name="location" id="location" class="autocomplete"
      onchange=
      "PHOTO_DIRECTORY.update_autocomplete('Entity_location_{{ id }}', 'location');">
        <option 
          {% if not entity.location %}
             selected="selected"
          {% endif %}
          value="location.-1"></option>
        {% for location in entities %}
        <option
          {% if location.id == entity.location %}
              selected="selected"
          {% endif %}
          value="location.{{ location.id }}">{{ location.name }}</option>
        {% endfor %}
</select></strong></p>

<p>Reports to: <strong>
    <a href="/?query={{ query }}&id={{ entity.reports_to.id }}"
      onclick="load_profile({{ entity.reports_to.id }}); return false;"
      >{{ entity.reports_to.name }}</a> &nbsp;
    <select name="reports_to" id="reports_to" class="autocomplete"
      onchange=
      "PHOTO_DIRECTORY.update_autocomplete('Entity_reports_to_{{ id }}', 'reports_to');">
        <option 
          {% if not entity.reports_to %}
             selected="selected"
          {% endif %}
          value="reports_to.-1"></option>
        {% for reports_to in entities %}
        <option
          {% if reports_to.id == entity.reports_to %}
              selected="selected"
          {% endif %}
          value="reports_to.{{ reports_to.id }}">{{ reports_to.name }}</option>
        {% endfor %}
</select></strong></p>

<p>Status:</p>
<div class="edit_textarea" id="Status_new_{{ id }}"></div>
{% for status in first_stati %}
<p>{{ status.text }}<br />
{{ status.username }}, 
<span class="timestamp">{{ status.format_timestamp }}</span></p>
{% endfor %}
{% if second_stati %}
    <p><a class="show_additional_stati"
    href="JavaScript:show_additional('stati');"
    ><span class="emphasized">+</span> Show all</a></p>
    <div class="additional_stati">
        {% for status in second_stati %}
            <p>{{ status.text }}<br />
            <span class="timestamp">{{ status.format_timestamp }}</span></p>
        {% endfor %}
    </div>
{% endif %}
<noscript>
    <style type="text/css">
        <!--

            .edit:after, .edit_textarea:after, .edit_rightclick:after
                {
                content: "";
                }

        // -->
    </style>
</noscript>